#version: '3.8'

services:
  # db:
  #   image: postgres:16.2
  #   container_name: db
  #   restart: always
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./backend/data/postgres:/var/lib/postgresql/data
  shylockgo:
    build:
      context: backend/scraper/
    image: shylockgo_scraper:0.0.4
    container_name: scraper_shylockgo
    hostname: scraper_shylockgo
    restart: always
      # depends_on:
      #   - db
    env_file:
      - ./backend/.env
    ports:
      - 5001:5000
    volumes:
      - ./backend/data/sqlite/:/var/lib/shylockgo/
        # apache:
        #   image: httpd:latest
        #   container_name: apache
        #   ports:
        #     - 8080:80
        #   volumes:
        #     - ./frontend/public/:/usr/local/apache2/htdocs
